<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\ZabbixSender;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:03.
 */
class ZabbixSenderTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ZabbixSender('localhost');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\ZabbixSender::preparePayload
     *
     * @todo   Implement testpreparePayload().
     */
    public function testpreparePayload(): void
    {
        $this->assertNotEmpty($this->object->preparePayload(new \MultiFlexi\Zabbix\Request\Packet()));
    }

    /**
     * @covers \MultiFlexi\ZabbixSender::zbxCreateHeader
     *
     * @todo   Implement testzbxCreateHeader().
     */
    public function testzbxCreateHeader(): void
    {
        $this->assertNotEmpty($this->object->zbxCreateHeader(10));
    }

    /**
     * @covers \MultiFlexi\ZabbixSender::send
     *
     * @todo   Implement testsend().
     */
    public function testsend(): void
    {
        $this->markTestIncomplete('This test requires a running Zabbix server.');
    }
}
