zabbix/multiflexi.conf etc/zabbix/zabbix_agent2.d
zabbix/multiflexi-template.xml usr/share/multiflexi/zabbix-templates


src/*.php	/usr/share/multiflexi-zabbix


src/MultiFlexi/Zabbix/*.php usr/lib/multiflexi-zabbix/MultiFlexi/Zabbix/
src/MultiFlexi/Zabbix/Exception/*.php usr/lib/multiflexi-zabbix/MultiFlexi/Zabbix/Exception/
src/MultiFlexi/Zabbix/Request/*.php usr/lib/multiflexi-zabbix/MultiFlexi/Zabbix/Request/
src/MultiFlexi/ZabbixSender.php usr/lib/multiflexi-zabbix/MultiFlexi/


src/MultiFlexi/Action/Zabbix.php /usr/share/php/MultiFlexi/Action


bin/multiflexi-zabbix-* usr/bin/
composer.json		/usr/lib/php/multiflexi-zabbix
debian/autoload.php	/usr/lib/php/multiflexi-zabbix

